### ISSUE TITLE
Multiple data fields declared on one line are not recognized correctly

### ISSUE THREAD

**Issue by Mnemotechnician** [Slava0135/vscode-robust-yaml#18]
The following syntax:
```cs
[DataField]
public SomeType FieldA, FieldB, FieldC;
```
Is valid for robust serialization generators and results in the creation of three distinct data fields. However, the extension seems to only recognize the first one (in this case FieldA), while others remain unrecognized.

An example:
<details>

![image](https://github.com/user-attachments/assets/9e46d5d6-d18e-4b9a-9fe1-5e1722c9a225)

![image](https://github.com/user-attachments/assets/8eb8103e-f25a-4773-b17c-c112662a3e31)

![image](https://github.com/user-attachments/assets/5d2f41e6-1438-4eea-a78a-51fdcfaae38f)

</details>

**Comment by Slava0135** [comment]
Didn't know that, will fix it 🔜
